[customizations.installer.kickstart]
contents = """
graphical --non-interactive
lang en_US.UTF-8
zerombr
clearpart --all --initlabel --disklabel=gpt
autopart --noswap --type xfs
network --bootproto=dhcp --device=link --activate --onboot=on
timezone --utc America/New_York
firstboot --enable
reboot
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Payloads",
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Subscription",
  "org.fedoraproject.Anaconda.Modules.Timezone",
  "org.fedoraproject.Anaconda.Modules.Users"
]
